# Generated by Django 5.1.3 on 2025-04-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
