# Generated by Django 5.1.3 on 2025-04-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_system', '0002_client_age_client_phone_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20, unique=True),
        ),
    ]
