# Generated by Django 5.1.3 on 2025-04-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_system', '0003_alter_client_email_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, default='0000000000', max_length=20, unique=True),
        ),
    ]
